// 確保全域變數存在，以便合併多冊字庫
if (typeof window.englishDb === 'undefined') {
    window.englishDb = {};
}
if (!window.englishDb["會考2000單"]) {
    window.englishDb["會考2000單"] = {};
}

// ==========================================
// 國中單字王 2000 單字 (主題分類版)
// ==========================================
window.englishDb["會考2000單"]["主題分類"] = {
    "01. 時間與季節": [
        { word: "January", translate: "一月" }, { word: "February", translate: "二月" }, { word: "March", translate: "三月" },
        { word: "April", translate: "四月" }, { word: "May", translate: "五月" }, { word: "June", translate: "六月" },
        { word: "July", translate: "七月" }, { word: "August", translate: "八月" }, { word: "September", translate: "九月" },
        { word: "October", translate: "十月" }, { word: "November", translate: "十一月" }, { word: "December", translate: "十二月" },
        { word: "Sunday", translate: "星期日" }, { word: "Monday", translate: "星期一" }, { word: "Tuesday", translate: "星期二" },
        { word: "Wednesday", translate: "星期三" }, { word: "Thursday", translate: "星期四" }, { word: "Friday", translate: "星期五" },
        { word: "Saturday", translate: "星期六" }, { word: "week", translate: "星期" }, { word: "weekday", translate: "週間" },
        { word: "weekend", translate: "週末" }, { word: "season", translate: "季節" }, { word: "spring", translate: "春天" },
        { word: "summer", translate: "夏天" }, { word: "autumn", translate: "秋天" }, { word: "winter", translate: "冬天" },
        { word: "ago", translate: "以前" }, { word: "ever", translate: "曾經" }, { word: "now", translate: "現在" },
        { word: "ancient", translate: "古代的" }, { word: "current", translate: "現行的" }, { word: "modern", translate: "現代的" },
        { word: "traditional", translate: "傳統的" }, { word: "present", translate: "現在的" }, { word: "past", translate: "過去的" },
        { word: "century", translate: "世紀" }, { word: "period", translate: "期間" }, { word: "childhood", translate: "童年時期" },
        { word: "youth", translate: "青少年時期" }, { word: "future", translate: "未來" }, { word: "a.m.", translate: "上午" },
        { word: "p.m.", translate: "午後" }, { word: "morning", translate: "早上" }, { word: "noon", translate: "中午" },
        { word: "afternoon", translate: "下午" }, { word: "eve", translate: "前夕" }, { word: "evening", translate: "傍晚" },
        { word: "night", translate: "晚上" }, { word: "midnight", translate: "午夜" }, { word: "dawn", translate: "黎明" },
        { word: "today", translate: "今天" }, { word: "yesterday", translate: "昨天" }, { word: "tomorrow", translate: "明天" },
        { word: "tonight", translate: "今晚" }, { word: "year", translate: "年" }, { word: "month", translate: "月" },
        { word: "day", translate: "天" }, { word: "daily", translate: "每日的" }, { word: "date", translate: "日期" },
        { word: "time", translate: "時間" }, { word: "o' clock", translate: "點鐘" }, { word: "hour", translate: "小時" },
        { word: "minute", translate: "分鐘" }
    ],
    "02. 天氣與大自然": [
        { word: "weather", translate: "天氣" }, { word: "climate", translate: "氣候" }, { word: "temperature", translate: "溫度" },
        { word: "air", translate: "空氣" }, { word: "typhoon", translate: "颱風" }, { word: "lightning", translate: "閃電" },
        { word: "rainbow", translate: "彩虹" }, { word: "snowman", translate: "雪人" }, { word: "cloud", translate: "雲" },
        { word: "cloudy", translate: "多雲的" }, { word: "fog", translate: "霧" }, { word: "foggy", translate: "有濃霧的" },
        { word: "rain", translate: "雨水" }, { word: "rainy", translate: "下雨的" }, { word: "snow", translate: "雪" },
        { word: "snowy", translate: "下雪的" }, { word: "storm", translate: "暴風雨" }, { word: "stormy", translate: "暴風雨的" },
        { word: "wind", translate: "風" }, { word: "windy", translate: "有風的" }, { word: "cold", translate: "冷的" },
        { word: "cool", translate: "涼爽的" }, { word: "freezing", translate: "酷寒的" }, { word: "hot", translate: "熱的" },
        { word: "humid", translate: "潮濕的" }, { word: "sunny", translate: "晴朗的" }, { word: "warm", translate: "溫暖的" },
        { word: "direction", translate: "方向" }, { word: "east", translate: "東方" }, { word: "north", translate: "北方" },
        { word: "south", translate: "南方" }, { word: "west", translate: "西方" }, { word: "universe", translate: "宇宙" },
        { word: "planet", translate: "行星" }, { word: "sun", translate: "太陽" }, { word: "moon", translate: "月亮" },
        { word: "star", translate: "星星" }, { word: "earth", translate: "地球" }, { word: "world", translate: "世界" },
        { word: "island", translate: "島嶼" }, { word: "land", translate: "陸地" }, { word: "coast", translate: "海岸" },
        { word: "ocean", translate: "海洋" }, { word: "sea", translate: "海" }, { word: "lake", translate: "湖" },
        { word: "pond", translate: "池塘" }, { word: "pool", translate: "水池" }, { word: "river", translate: "河" },
        { word: "stream", translate: "溪流" }, { word: "waterfalls", translate: "瀑布" }, { word: "desert", translate: "沙漠" },
        { word: "rock", translate: "岩石" }, { word: "stone", translate: "石頭" }, { word: "sand", translate: "沙子" },
        { word: "forest", translate: "森林" }, { word: "valley", translate: "山谷" }, { word: "mountain", translate: "山" },
        { word: "hill", translate: "小山坡" }, { word: "sky", translate: "天空" }, { word: "thunder", translate: "雷" },
        { word: "fire", translate: "火" }, { word: "ice", translate: "冰" }, { word: "nature", translate: "大自然" },
        { word: "natural", translate: "自然的" }, { word: "shine", translate: "照耀" }, { word: "plant", translate: "植物" },
        { word: "grass", translate: "青草" }, { word: "flower", translate: "花" }, { word: "cotton", translate: "棉花" },
        { word: "rose", translate: "玫瑰花" }, { word: "tree", translate: "樹" }, { word: "leaf", translate: "樹葉" },
        { word: "seed", translate: "種子" }, { word: "root", translate: "根" }, { word: "woods", translate: "樹林" },
        { word: "grow", translate: "成長" }
    ],
    "03. 動物與昆蟲": [
        { word: "animal", translate: "動物" }, { word: "pet", translate: "寵物" }, { word: "bird", translate: "鳥" },
        { word: "duck", translate: "鴨子" }, { word: "goose", translate: "鵝" }, { word: "chicken", translate: "小雞" },
        { word: "hen", translate: "母雞" }, { word: "turkey", translate: "火雞" }, { word: "eagle", translate: "老鷹" },
        { word: "parrot", translate: "鸚鵡" }, { word: "pigeon", translate: "鴿子" }, { word: "swallow", translate: "燕子" },
        { word: "swan", translate: "天鵝" }, { word: "bat", translate: "蝙蝠" }, { word: "bear", translate: "熊" },
        { word: "koala", translate: "無尾熊" }, { word: "panda", translate: "貓熊" }, { word: "cow", translate: "母牛" },
        { word: "ox", translate: "公牛" }, { word: "cat", translate: "貓" }, { word: "kitten", translate: "小貓" },
        { word: "deer", translate: "鹿" }, { word: "dinosaur", translate: "恐龍" }, { word: "dog", translate: "狗" },
        { word: "puppy", translate: "小狗" }, { word: "donkey", translate: "驢子" }, { word: "elephant", translate: "大象" },
        { word: "fox", translate: "狐狸" }, { word: "goat", translate: "山羊" }, { word: "sheep", translate: "綿羊" },
        { word: "lamb", translate: "小羊" }, { word: "hippo", translate: "河馬" }, { word: "horse", translate: "馬" },
        { word: "zebra", translate: "斑馬" }, { word: "kangaroo", translate: "袋鼠" }, { word: "mouse", translate: "老鼠" },
        { word: "rat", translate: "大老鼠" }, { word: "lion", translate: "獅子" }, { word: "tiger", translate: "老虎" },
        { word: "wolf", translate: "野狼" }, { word: "monkey", translate: "猴子" }, { word: "pig", translate: "豬" },
        { word: "rabbit", translate: "兔子" }, { word: "frog", translate: "青蛙" }, { word: "turtle", translate: "烏龜" },
        { word: "snail", translate: "蝸牛" }, { word: "snake", translate: "蛇" }, { word: "spider", translate: "蜘蛛" },
        { word: "worm", translate: "蠕蟲" }, { word: "crab", translate: "螃蟹" }, { word: "dolphin", translate: "海豚" },
        { word: "fish", translate: "魚" }, { word: "shark", translate: "鯊魚" }, { word: "whale", translate: "鯨魚" },
        { word: "shrimp", translate: "蝦子" }, { word: "insect", translate: "昆蟲" }, { word: "ant", translate: "螞蟻" },
        { word: "bee", translate: "蜜蜂" }, { word: "bug", translate: "蟲子" }, { word: "cockroach", translate: "蟑螂" },
        { word: "butterfly", translate: "蝴蝶" }, { word: "mosquito", translate: "蚊子" }
    ],
    "04. 飲食與水果": [
        { word: "breakfast", translate: "早餐" }, { word: "brunch", translate: "早午餐" }, { word: "lunch", translate: "午餐" },
        { word: "dinner", translate: "晚餐" }, { word: "supper", translate: "晚餐" }, { word: "meal", translate: "一餐" },
        { word: "buffet", translate: "自助餐" }, { word: "menu", translate: "菜單" }, { word: "delicious", translate: "美味的" },
        { word: "yummy", translate: "好吃的" }, { word: "diet", translate: "飲食" }, { word: "eat", translate: "吃" },
        { word: "food", translate: "食物" }, { word: "meat", translate: "肉" }, { word: "barbecue", translate: "烤肉" },
        { word: "beef", translate: "牛肉" }, { word: "steak", translate: "牛排" }, { word: "pork", translate: "豬肉" },
        { word: "ham", translate: "火腿" }, { word: "hot dog", translate: "熱狗" }, { word: "dumpling", translate: "餃子" },
        { word: "seafood", translate: "海鮮" }, { word: "egg", translate: "蛋" }, { word: "bread", translate: "麵包" },
        { word: "bun", translate: "小圓麵包" }, { word: "sandwich", translate: "三明治" }, { word: "toast", translate: "烤土司" },
        { word: "burger", translate: "漢堡" }, { word: "hamburger", translate: "漢堡" }, { word: "French fries", translate: "薯條" },
        { word: "pizza", translate: "披薩" }, { word: "spaghetti", translate: "義大利麵" }, { word: "noodle", translate: "麵" },
        { word: "rice", translate: "飯" }, { word: "soup", translate: "湯" }, { word: "salad", translate: "沙拉" },
        { word: "tofu", translate: "豆腐" }, { word: "pie", translate: "派" }, { word: "cake", translate: "蛋糕" },
        { word: "candy", translate: "糖果" }, { word: "cereal", translate: "麥片" }, { word: "cheese", translate: "乳酪" },
        { word: "chocolate", translate: "巧克力" }, { word: "cookie", translate: "餅乾" }, { word: "dessert", translate: "甜點" },
        { word: "doughnut", translate: "甜甜圈" }, { word: "ice cream", translate: "冰淇淋" }, { word: "popcorn", translate: "爆米花" },
        { word: "nut", translate: "堅果" }, { word: "snack", translate: "點心" }, { word: "butter", translate: "奶油" },
        { word: "cream", translate: "鮮奶油" }, { word: "flour", translate: "麵粉" }, { word: "honey", translate: "蜂蜜" },
        { word: "ketchup", translate: "番茄醬" }, { word: "oil", translate: "油" }, { word: "pepper", translate: "胡椒" },
        { word: "salt", translate: "鹽" }, { word: "soy sauce", translate: "醬油" }, { word: "sugar", translate: "糖" },
        { word: "vinegar", translate: "醋" }, { word: "fruit", translate: "水果" }, { word: "apple", translate: "蘋果" },
        { word: "banana", translate: "香蕉" }, { word: "grape", translate: "葡萄" }, { word: "guava", translate: "芭樂" },
        { word: "lemon", translate: "檸檬" }, { word: "mango", translate: "芒果" }, { word: "orange", translate: "柳橙" },
        { word: "papaya", translate: "木瓜" }, { word: "peach", translate: "桃子" }, { word: "pear", translate: "梨子" },
        { word: "pineapple", translate: "鳳梨" }, { word: "strawberry", translate: "草莓" }, { word: "tangerine", translate: "橘子" },
        { word: "watermelon", translate: "西瓜" }, { word: "vegetable", translate: "蔬菜" }, { word: "bean", translate: "豆" },
        { word: "cabbage", translate: "高麗菜" }, { word: "carrot", translate: "紅蘿蔔" }, { word: "corn", translate: "玉米" },
        { word: "lettuce", translate: "萵苣" }, { word: "onion", translate: "洋蔥" }, { word: "potato", translate: "馬鈴薯" },
        { word: "pumpkin", translate: "南瓜" }, { word: "tomato", translate: "番茄" }, { word: "drink", translate: "飲料" },
        { word: "beer", translate: "啤酒" }, { word: "coffee", translate: "咖啡" }, { word: "cola", translate: "可樂" },
        { word: "juice", translate: "果汁" }, { word: "milk", translate: "牛奶" }, { word: "soda", translate: "蘇打水" },
        { word: "soft drink", translate: "汽水" }, { word: "tea", translate: "茶" }
    ],
    "05. 身體與健康": [
        { word: "body", translate: "身體" }, { word: "head", translate: "頭" }, { word: "face", translate: "臉" },
        { word: "eye", translate: "眼睛" }, { word: "ear", translate: "耳朵" }, { word: "nose", translate: "鼻子" },
        { word: "lip", translate: "嘴唇" }, { word: "mouth", translate: "嘴巴" }, { word: "chin", translate: "下巴" },
        { word: "neck", translate: "脖子" }, { word: "shoulder", translate: "肩膀" }, { word: "arm", translate: "手臂" },
        { word: "hand", translate: "手" }, { word: "wrist", translate: "手腕" }, { word: "finger", translate: "手指" },
        { word: "thumb", translate: "拇指" }, { word: "back", translate: "背部" }, { word: "waist", translate: "腰" },
        { word: "hip", translate: "臀部" }, { word: "leg", translate: "腿" }, { word: "knee", translate: "膝蓋" },
        { word: "ankle", translate: "腳踝" }, { word: "foot", translate: "腳" }, { word: "toe", translate: "腳趾" },
        { word: "beard", translate: "落腮鬍" }, { word: "hair", translate: "頭髮" }, { word: "nail", translate: "指甲" },
        { word: "skin", translate: "皮膚" }, { word: "blood", translate: "血液" }, { word: "bone", translate: "骨頭" },
        { word: "tooth", translate: "牙齒" }, { word: "heart", translate: "心臟" }, { word: "tongue", translate: "舌頭" },
        { word: "throat", translate: "喉嚨" }, { word: "stomach", translate: "胃" }, { word: "health", translate: "健康" },
        { word: "cancer", translate: "癌症" }, { word: "flu", translate: "流行性感冒" }, { word: "cough", translate: "咳嗽" },
        { word: "fever", translate: "發燒" }, { word: "wound", translate: "傷口" }, { word: "headache", translate: "頭痛" },
        { word: "stomachache", translate: "胃痛" }, { word: "toothache", translate: "牙痛" }, { word: "pain", translate: "疼痛" },
        { word: "dizzy", translate: "暈眩的" }, { word: "healthy", translate: "健康的" }, { word: "well", translate: "健康的" },
        { word: "ill", translate: "生病的" }, { word: "sick", translate: "生病的" }, { word: "painful", translate: "痛苦的" },
        { word: "sore", translate: "疼痛的" }, { word: "strong", translate: "強壯的" }, { word: "weak", translate: "虛弱的" },
        { word: "cure", translate: "治癒" }, { word: "hurt", translate: "受傷" }, { word: "jam", translate: "夾傷" },
        { word: "treat", translate: "治療" }, { word: "operation", translate: "手術" }, { word: "sense", translate: "感官" },
        { word: "sight", translate: "視覺" }, { word: "voice", translate: "聲音" }, { word: "blind", translate: "瞎的" },
        { word: "deaf", translate: "耳聾的" }, { word: "dumb", translate: "啞的" }, { word: "hear", translate: "聽見" },
        { word: "listen", translate: "聽" }, { word: "see", translate: "看見" }, { word: "look", translate: "看" },
        { word: "speak", translate: "說話" }, { word: "say", translate: "說" }, { word: "talk", translate: "說話" },
        { word: "tell", translate: "告訴" }, { word: "smell", translate: "聞" }, { word: "taste", translate: "品嚐" },
        { word: "bitter", translate: "苦的" }, { word: "sour", translate: "酸的" }, { word: "sweet", translate: "甜的" },
        { word: "hungry", translate: "飢餓的" }, { word: "thirsty", translate: "口渴的" }
    ],
    "06. 情感與特質": [
        { word: "emotion", translate: "情緒" }, { word: "feeling", translate: "感覺" }, { word: "joy", translate: "喜悅" },
        { word: "pleasure", translate: "愉快" }, { word: "afraid", translate: "害怕的" }, { word: "angry", translate: "生氣的" },
        { word: "mad", translate: "發瘋的" }, { word: "bored", translate: "感到厭煩的" }, { word: "excited", translate: "感到興奮的" },
        { word: "jealous", translate: "嫉妒的" }, { word: "lonely", translate: "寂寞的" }, { word: "nervous", translate: "緊張的" },
        { word: "glad", translate: "高興的" }, { word: "happy", translate: "快樂的" }, { word: "pleased", translate: "滿意的" },
        { word: "sad", translate: "悲傷的" }, { word: "sorry", translate: "抱歉的" }, { word: "unhappy", translate: "不快樂的" },
        { word: "surprised", translate: "感到驚訝的" }, { word: "feel", translate: "感覺" }, { word: "admire", translate: "欽佩" },
        { word: "anger", translate: "激怒" }, { word: "envy", translate: "羨慕" }, { word: "fear", translate: "畏懼" },
        { word: "hate", translate: "仇恨" }, { word: "regret", translate: "懊悔" }, { word: "respect", translate: "尊敬" },
        { word: "worry", translate: "擔心" }, { word: "careful", translate: "仔細的" }, { word: "careless", translate: "粗心的" },
        { word: "childish", translate: "幼稚的" }, { word: "childlike", translate: "天真的" }, { word: "evil", translate: "邪惡的" },
        { word: "friendly", translate: "親切的" }, { word: "kind", translate: "友善的" }, { word: "funny", translate: "滑稽的" },
        { word: "naughty", translate: "頑皮的" }, { word: "generous", translate: "慷慨的" }, { word: "stingy", translate: "小氣的" },
        { word: "selfish", translate: "自私的" }, { word: "gentle", translate: "溫和的" }, { word: "good", translate: "好的" },
        { word: "bad", translate: "壞的" }, { word: "diligent", translate: "勤勉的" }, { word: "hard-working", translate: "勤勉的" },
        { word: "lazy", translate: "懶惰的" }, { word: "honest", translate: "誠實的" }, { word: "dishonest", translate: "不誠實的" },
        { word: "sincere", translate: "真誠的" }, { word: "responsible", translate: "負責任的" }, { word: "humble", translate: "謙虛的" },
        { word: "proud", translate: "驕傲的" }, { word: "humorous", translate: "幽默的" }, { word: "polite", translate: "有禮貌的" },
        { word: "impolite", translate: "沒禮貌的" }, { word: "rude", translate: "無禮的" }, { word: "intelligent", translate: "明智的" },
        { word: "clever", translate: "聰明的" }, { word: "smart", translate: "聰明的" }, { word: "wise", translate: "有智慧的" },
        { word: "foolish", translate: "愚蠢的" }, { word: "silly", translate: "傻的" }, { word: "stupid", translate: "愚笨的" },
        { word: "shy", translate: "害羞的" }, { word: "talkative", translate: "愛說話的" }, { word: "goodness", translate: "善良" },
        { word: "honesty", translate: "誠實" }, { word: "humor", translate: "幽默" }
    ],
    "07. 交通與地點": [
        { word: "country", translate: "國家" }, { word: "nation", translate: "國家" }, { word: "U. S. A.", translate: "美國" },
        { word: "America", translate: "美國" }, { word: "American", translate: "美國人" }, { word: "China", translate: "中國" },
        { word: "R. O. C.", translate: "中華民國" }, { word: "Taiwan", translate: "臺灣" }, { word: "national", translate: "國家的" },
        { word: "foreigner", translate: "外國人" }, { word: "foreign", translate: "外國的" }, { word: "local", translate: "本地的" },
        { word: "international", translate: "國際的" }, { word: "overseas", translate: "國外的" }, { word: "abroad", translate: "到國外" },
        { word: "elect", translate: "選舉" }, { word: "vote", translate: "投票" }, { word: "government", translate: "政府" },
        { word: "downtown", translate: "市區" }, { word: "town", translate: "城鎮" }, { word: "village", translate: "村落" },
        { word: "block", translate: "街道" }, { word: "corner", translate: "街角" }, { word: "street", translate: "街道" },
        { word: "road", translate: "道路" }, { word: "way", translate: "道路" }, { word: "highway", translate: "公路" },
        { word: "sidewalk", translate: "人行道" }, { word: "underpass", translate: "地下道" }, { word: "path", translate: "小徑" },
        { word: "bridge", translate: "橋" }, { word: "overpass", translate: "天橋" }, { word: "tunnel", translate: "隧道" },
        { word: "entrance", translate: "入口" }, { word: "exit", translate: "出口" }, { word: "ground", translate: "地面" },
        { word: "platform", translate: "月台" }, { word: "sign", translate: "標誌" }, { word: "stop", translate: "車站" },
        { word: "traffic", translate: "交通" }, { word: "airplane", translate: "飛機" }, { word: "airlines", translate: "航空公司" },
        { word: "flight", translate: "飛機班次" }, { word: "helicopter", translate: "直昇機" }, { word: "ship", translate: "大船" },
        { word: "boat", translate: "小船" }, { word: "train", translate: "火車" }, { word: "railroad", translate: "鐵路" },
        { word: "railway", translate: "鐵路" }, { word: "subway", translate: "地鐵" }, { word: "metro", translate: "地鐵" },
        { word: "MRT", translate: "捷運" }, { word: "bus", translate: "公車" }, { word: "truck", translate: "卡車" },
        { word: "jeep", translate: "吉普車" }, { word: "ambulance", translate: "救護車" }, { word: "car", translate: "汽車" },
        { word: "taxi", translate: "計程車" }, { word: "motorcycle", translate: "摩托車" }, { word: "scooter", translate: "機車" },
        { word: "bicycle", translate: "單車" }, { word: "board", translate: "上(交通工具)" }, { word: "drive", translate: "駕駛" },
        { word: "ride", translate: "騎" }, { word: "row", translate: "划船" }, { word: "sail", translate: "航行" },
        { word: "place", translate: "地方" }, { word: "airport", translate: "機場" }, { word: "station", translate: "車站" },
        { word: "bank", translate: "銀行" }, { word: "post office", translate: "郵局" }, { word: "department store", translate: "百貨公司" },
        { word: "mall", translate: "購物中心" }, { word: "market", translate: "市場" }, { word: "supermarket", translate: "超市" },
        { word: "store", translate: "商店" }, { word: "shop", translate: "商店" }, { word: "convenience store", translate: "便利商店" },
        { word: "bakery", translate: "麵包店" }, { word: "bookstore", translate: "書店" }, { word: "drugstore", translate: "藥妝店" },
        { word: "cafeteria", translate: "自助餐館" }, { word: "restaurant", translate: "餐廳" }, { word: "gym", translate: "體育館" },
        { word: "hospital", translate: "醫院" }, { word: "hotel", translate: "旅館" }, { word: "library", translate: "圖書館" },
        { word: "museum", translate: "博物館" }, { word: "park", translate: "公園" }, { word: "square", translate: "廣場" },
        { word: "playground", translate: "操場" }, { word: "parking lot", translate: "停車場" }, { word: "theater", translate: "戲院" },
        { word: "zoo", translate: "動物園" }, { word: "court", translate: "法庭" }, { word: "factory", translate: "工廠" },
        { word: "farm", translate: "農場" }, { word: "temple", translate: "寺廟" }, { word: "company", translate: "公司" }
    ],
    "08. 學校與辦公": [
        { word: "education", translate: "教育" }, { word: "university", translate: "大學" }, { word: "college", translate: "學院" },
        { word: "senior high school", translate: "高中" }, { word: "junior high school", translate: "國中" }, { word: "elementary school", translate: "小學" },
        { word: "kindergarten", translate: "幼稚園" }, { word: "school", translate: "學校" }, { word: "campus", translate: "校園" },
        { word: "semester", translate: "學期" }, { word: "grade", translate: "成績" }, { word: "course", translate: "課程" },
        { word: "lesson", translate: "功課" }, { word: "exam", translate: "考試" }, { word: "quiz", translate: "測驗" },
        { word: "test", translate: "測試" }, { word: "homework", translate: "功課" }, { word: "degree", translate: "學位" },
        { word: "beginner", translate: "初學者" }, { word: "group", translate: "小組" }, { word: "club", translate: "社團" },
        { word: "bell", translate: "鈴" }, { word: "blackboard", translate: "黑板" }, { word: "chair", translate: "椅子" },
        { word: "chalk", translate: "粉筆" }, { word: "textbook", translate: "教科書" }, { word: "workbook", translate: "作業簿" },
        { word: "learn", translate: "學習" }, { word: "study", translate: "學習" }, { word: "review", translate: "複習" },
        { word: "subject", translate: "科目" }, { word: "art", translate: "美術" }, { word: "biology", translate: "生物學" },
        { word: "chemistry", translate: "化學" }, { word: "Chinese", translate: "中文" }, { word: "English", translate: "英文" },
        { word: "geography", translate: "地理學" }, { word: "history", translate: "歷史" }, { word: "math", translate: "數學" },
        { word: "PE", translate: "體育" }, { word: "physics", translate: "物理學" }, { word: "science", translate: "科學" },
        { word: "office", translate: "辦公室" }, { word: "department", translate: "部門" }, { word: "chart", translate: "圖表" },
        { word: "form", translate: "表格" }, { word: "list", translate: "清單" }, { word: "copy", translate: "副本" },
        { word: "e-mail", translate: "電子郵件" }, { word: "mail", translate: "郵件" }, { word: "letter", translate: "信件" },
        { word: "message", translate: "訊息" }, { word: "file", translate: "文件夾" }, { word: "information", translate: "資訊" },
        { word: "knowledge", translate: "知識" }, { word: "Internet", translate: "網路" }, { word: "link", translate: "連結" },
        { word: "computer", translate: "電腦" }, { word: "screen", translate: "螢幕" }, { word: "printer", translate: "印表機" },
        { word: "work", translate: "工作" }, { word: "interview", translate: "面試" }, { word: "project", translate: "專案" },
        { word: "matter", translate: "事情" }, { word: "problem", translate: "問題" }, { word: "method", translate: "方法" },
        { word: "plan", translate: "計畫" }, { word: "meeting", translate: "會議" }, { word: "report", translate: "報告" },
        { word: "member", translate: "成員" }, { word: "team", translate: "團隊" }, { word: "call", translate: "打電話" },
        { word: "dial", translate: "撥號" }, { word: "employ", translate: "僱用" }, { word: "hire", translate: "僱用" },
        { word: "quit", translate: "離職" }, { word: "interrupt", translate: "打斷" }, { word: "business", translate: "生意" },
        { word: "trade", translate: "交易" }, { word: "contract", translate: "合約" }, { word: "duty", translate: "義務" },
        { word: "income", translate: "收入" }, { word: "rent", translate: "租金" }, { word: "bill", translate: "帳單" },
        { word: "fee", translate: "費用" }, { word: "price", translate: "價格" }, { word: "credit card", translate: "信用卡" },
        { word: "cash", translate: "現金" }, { word: "coin", translate: "硬幣" }, { word: "money", translate: "錢" },
        { word: "cent", translate: "一分" }, { word: "dollar", translate: "元" }, { word: "pound", translate: "英鎊" },
        { word: "sell", translate: "賣出" }, { word: "buy", translate: "購買" }, { word: "pay", translate: "支付" },
        { word: "charge", translate: "收費" }, { word: "cost", translate: "花費" }, { word: "spend", translate: "花費" },
        { word: "cheap", translate: "便宜的" }, { word: "expensive", translate: "昂貴的" }, { word: "free", translate: "免費的" }
    ],
    "09. 人物與家庭": [
        { word: "family", translate: "家庭" }, { word: "aunt", translate: "阿姨" }, { word: "uncle", translate: "叔叔" },
        { word: "brother", translate: "兄弟" }, { word: "sister", translate: "姊妹" }, { word: "cousin", translate: "表兄弟姊妹" },
        { word: "daughter", translate: "女兒" }, { word: "son", translate: "兒子" }, { word: "father", translate: "爸爸" },
        { word: "mother", translate: "媽媽" }, { word: "parent", translate: "雙親" }, { word: "granddaughter", translate: "孫女" },
        { word: "grandson", translate: "孫子" }, { word: "grandfather", translate: "祖父" }, { word: "grandmother", translate: "祖母" },
        { word: "husband", translate: "丈夫" }, { word: "wife", translate: "妻子" }, { word: "nephew", translate: "侄子" },
        { word: "niece", translate: "侄女" }, { word: "relative", translate: "親戚" }, { word: "human", translate: "人類" },
        { word: "person", translate: "個人" }, { word: "people", translate: "人們" }, { word: "adult", translate: "成人" },
        { word: "baby", translate: "嬰孩" }, { word: "child", translate: "小孩子" }, { word: "kid", translate: "孩子" },
        { word: "teenager", translate: "青少年" }, { word: "boy", translate: "男孩" }, { word: "girl", translate: "女孩" },
        { word: "gentleman", translate: "紳士" }, { word: "lady", translate: "淑女" }, { word: "ma'am", translate: "女士" },
        { word: "sir", translate: "先生" }, { word: "Miss", translate: "小姐" }, { word: "Mr.", translate: "先生" },
        { word: "Mrs.", translate: "太太" }, { word: "Ms.", translate: "女士" }, { word: "man", translate: "男人" },
        { word: "woman", translate: "女人" }, { word: "female", translate: "女性的" }, { word: "male", translate: "男性的" },
        { word: "job", translate: "職業" }, { word: "actor", translate: "男演員" }, { word: "actress", translate: "女演員" },
        { word: "model", translate: "模特兒" }, { word: "magician", translate: "魔術師" }, { word: "artist", translate: "藝術家" },
        { word: "musician", translate: "音樂家" }, { word: "scientist", translate: "科學家" }, { word: "writer", translate: "作家" },
        { word: "president", translate: "總統" }, { word: "diplomat", translate: "外交官" }, { word: "officer", translate: "軍官" },
        { word: "guard", translate: "警衛" }, { word: "judge", translate: "法官" }, { word: "lawyer", translate: "律師" },
        { word: "doctor", translate: "醫生" }, { word: "dentist", translate: "牙醫" }, { word: "nurse", translate: "護士" },
        { word: "journalist", translate: "新聞記者" }, { word: "reporter", translate: "記者" }, { word: "principal", translate: "校長" },
        { word: "professor", translate: "教授" }, { word: "teacher", translate: "老師" }, { word: "student", translate: "學生" },
        { word: "police", translate: "警察" }, { word: "soldier", translate: "士兵" }, { word: "driver", translate: "司機" },
        { word: "captain", translate: "機長" }, { word: "cowboy", translate: "牛仔" }, { word: "farmer", translate: "農夫" },
        { word: "fisherman", translate: "漁夫" }, { word: "barber", translate: "理髮師" }, { word: "hairdresser", translate: "美髮師" },
        { word: "shopkeeper", translate: "店主" }, { word: "vendor", translate: "小販" }, { word: "salesman", translate: "推銷員" },
        { word: "waiter", translate: "服務生" }, { word: "waitress", translate: "女服務生" }, { word: "mail carrier", translate: "郵差" },
        { word: "worker", translate: "工人" }, { word: "mechanic", translate: "技工" }, { word: "painter", translate: "油漆工" },
        { word: "baby sitter", translate: "保母" }, { word: "housewife", translate: "家庭主婦" }, { word: "engineer", translate: "工程師" },
        { word: "priest", translate: "牧師" }, { word: "coach", translate: "教練" }, { word: "sailor", translate: "水手" },
        { word: "singer", translate: "歌手" }, { word: "businessman", translate: "商人" }, { word: "boss", translate: "老板" },
        { word: "secretary", translate: "秘書" }, { word: "manager", translate: "經理" }, { word: "clerk", translate: "職員" },
        { word: "assistant", translate: "助理" }, { word: "character", translate: "角色" }, { word: "role", translate: "角色" },
        { word: "angel", translate: "天使" }, { word: "dragon", translate: "龍" }, { word: "ghost", translate: "鬼" },
        { word: "god", translate: "神" }, { word: "monster", translate: "怪物" }, { word: "customer", translate: "顧客" },
        { word: "guest", translate: "客人" }, { word: "passenger", translate: "乘客" }, { word: "enemy", translate: "敵人" },
        { word: "neighbor", translate: "鄰居" }, { word: "friend", translate: "朋友" }, { word: "partner", translate: "夥伴" },
        { word: "stranger", translate: "陌生人" }, { word: "visitor", translate: "訪客" }, { word: "fool", translate: "傻瓜" },
        { word: "genius", translate: "天才" }, { word: "giant", translate: "巨人" }, { word: "hero", translate: "英雄" },
        { word: "hunter", translate: "獵人" }, { word: "host", translate: "主人" }, { word: "leader", translate: "領導者" },
        { word: "player", translate: "選手" }, { word: "thief", translate: "小偷" }, { word: "king", translate: "國王" },
        { word: "queen", translate: "皇后" }, { word: "prince", translate: "王子" }, { word: "princess", translate: "公主" },
        { word: "servant", translate: "僕人" }
    ],
    "10. 居家與生活": [
        { word: "apartment", translate: "公寓" }, { word: "castle", translate: "城堡" }, { word: "building", translate: "建築物" },
        { word: "house", translate: "房子" }, { word: "gate", translate: "大門" }, { word: "hall", translate: "大廳" },
        { word: "garden", translate: "花園" }, { word: "yard", translate: "庭院" }, { word: "garage", translate: "車庫" },
        { word: "room", translate: "房間" }, { word: "living room", translate: "客廳" }, { word: "dining room", translate: "飯廳" },
        { word: "kitchen", translate: "廚房" }, { word: "bedroom", translate: "臥室" }, { word: "bathroom", translate: "浴室" },
        { word: "restroom", translate: "洗手間" }, { word: "basement", translate: "地下室" }, { word: "balcony", translate: "陽台" },
        { word: "roof", translate: "屋頂" }, { word: "ceiling", translate: "天花板" }, { word: "floor", translate: "地板" },
        { word: "stairs", translate: "樓梯" }, { word: "wall", translate: "牆壁" }, { word: "window", translate: "窗戶" },
        { word: "fence", translate: "柵欄" }, { word: "home", translate: "家" }, { word: "furniture", translate: "家具" },
        { word: "armchair", translate: "扶手椅" }, { word: "basket", translate: "籃子" }, { word: "bed", translate: "床" },
        { word: "bench", translate: "長椅" }, { word: "blanket", translate: "毯子" }, { word: "bookcase", translate: "書架" },
        { word: "shelf", translate: "架子" }, { word: "carpet", translate: "地毯" }, { word: "closet", translate: "衣櫥" },
        { word: "couch", translate: "沙發" }, { word: "sofa", translate: "沙發" }, { word: "curtain", translate: "窗簾" },
        { word: "desk", translate: "書桌" }, { word: "table", translate: "桌子" }, { word: "door", translate: "門" },
        { word: "drawer", translate: "抽屜" }, { word: "dresser", translate: "梳妝台" }, { word: "comb", translate: "梳子" },
        { word: "air conditioner", translate: "冷氣機" }, { word: "heater", translate: "暖氣機" }, { word: "fan", translate: "電扇" },
        { word: "alarm", translate: "鬧鐘" }, { word: "clock", translate: "時鐘" }, { word: "lamp", translate: "檯燈" },
        { word: "mirror", translate: "鏡子" }, { word: "pillow", translate: "枕頭" }, { word: "radio", translate: "收音機" },
        { word: "telephone", translate: "電話" }, { word: "television", translate: "電視" }, { word: "decorate", translate: "裝飾" },
        { word: "design", translate: "設計" }, { word: "bath", translate: "沐浴" }, { word: "faucet", translate: "水龍頭" },
        { word: "toilet", translate: "馬桶" }, { word: "tub", translate: "浴缸" }, { word: "toothbrush", translate: "牙刷" },
        { word: "towel", translate: "毛巾" }, { word: "soap", translate: "肥皂" }, { word: "dryer", translate: "烘乾機" },
        { word: "shower", translate: "淋浴" }, { word: "bathe", translate: "洗澡" }, { word: "bottle", translate: "瓶子" },
        { word: "lid", translate: "蓋子" }, { word: "bowl", translate: "碗" }, { word: "chopsticks", translate: "筷子" },
        { word: "cup", translate: "杯子" }, { word: "glass", translate: "玻璃杯" }, { word: "dish", translate: "盤子" },
        { word: "plate", translate: "盤子" }, { word: "fork", translate: "叉子" }, { word: "knife", translate: "刀子" },
        { word: "spoon", translate: "湯匙" }, { word: "saucer", translate: "醬料碟" }, { word: "can", translate: "罐頭" },
        { word: "straw", translate: "吸管" }, { word: "napkin", translate: "餐巾紙" }, { word: "pan", translate: "平底鍋" },
        { word: "pot", translate: "鍋子" }, { word: "wok", translate: "炒菜鍋" }, { word: "teapot", translate: "茶壺" },
        { word: "freezer", translate: "冰箱" }, { word: "refrigerator", translate: "冰箱" }, { word: "microwave", translate: "微波爐" },
        { word: "oven", translate: "烤箱" }, { word: "gas", translate: "瓦斯" }, { word: "stove", translate: "爐灶" },
        { word: "sink", translate: "水槽" }, { word: "bake", translate: "烤" }, { word: "boil", translate: "煮沸" },
        { word: "cook", translate: "煮" }, { word: "fry", translate: "炒" }, { word: "steam", translate: "蒸" },
        { word: "slice", translate: "切成薄片" }, { word: "housework", translate: "家事" }, { word: "brush", translate: "刷子" },
        { word: "bucket", translate: "水桶" }, { word: "mop", translate: "拖把" }, { word: "garbage", translate: "垃圾" },
        { word: "trash", translate: "垃圾" }, { word: "dirty", translate: "骯髒的" }, { word: "sweep", translate: "清掃" },
        { word: "album", translate: "相簿" }, { word: "book", translate: "書本" }, { word: "calendar", translate: "日曆" },
        { word: "comic", translate: "漫畫" }, { word: "diary", translate: "日記" }, { word: "dictionary", translate: "字典" },
        { word: "magazine", translate: "雜誌" }, { word: "map", translate: "地圖" }, { word: "newspaper", translate: "報紙" },
        { word: "note", translate: "筆記" }, { word: "novel", translate: "小說" }, { word: "page", translate: "頁" },
        { word: "paper", translate: "紙張" }, { word: "postcard", translate: "明信片" }, { word: "sheet", translate: "紙張" },
        { word: "stationery", translate: "文具" }, { word: "pen", translate: "筆" }, { word: "pencil", translate: "鉛筆" },
        { word: "eraser", translate: "橡皮擦" }, { word: "ruler", translate: "尺" }, { word: "crayon", translate: "蠟筆" },
        { word: "marker", translate: "麥克筆" }, { word: "envelope", translate: "信封" }, { word: "glue", translate: "膠水" },
        { word: "ink", translate: "墨水" }, { word: "paste", translate: "漿糊" }, { word: "notebook", translate: "筆記本" },
        { word: "pin", translate: "別針" }, { word: "stamp", translate: "郵票" }, { word: "thing", translate: "事物" },
        { word: "box", translate: "盒子" }, { word: "cage", translate: "籠子" }, { word: "cellphone", translate: "手機" },
        { word: "chess", translate: "西洋棋" }, { word: "diamond", translate: "鑽石" }, { word: "doll", translate: "洋娃娃" },
        { word: "flag", translate: "旗子" }, { word: "flashlight", translate: "手電筒" }, { word: "gun", translate: "槍" },
        { word: "key", translate: "鑰匙" }, { word: "kite", translate: "風箏" }, { word: "lantern", translate: "燈籠" },
        { word: "mat", translate: "草蓆" }, { word: "needle", translate: "針" }, { word: "net", translate: "網子" },
        { word: "package", translate: "包裹" }, { word: "pipe", translate: "管子" }, { word: "raincoat", translate: "雨衣" },
        { word: "rope", translate: "繩索" }, { word: "ticket", translate: "票券" }, { word: "toy", translate: "玩具" },
        { word: "tube", translate: "管子" }, { word: "umbrella", translate: "雨傘" }, { word: "wheel", translate: "輪胎" }
    ],
    "11. 衣物與顏色": [
        { word: "clothes", translate: "衣服" }, { word: "blouse", translate: "襯衫" }, { word: "shirt", translate: "襯衫" },
        { word: "T-shirt", translate: "T 恤衫" }, { word: "sweater", translate: "毛衣" }, { word: "dress", translate: "洋裝" },
        { word: "skirt", translate: "裙子" }, { word: "jeans", translate: "牛仔褲" }, { word: "pants", translate: "長褲" },
        { word: "trousers", translate: "長褲" }, { word: "shorts", translate: "短褲" }, { word: "vest", translate: "背心" },
        { word: "coat", translate: "大衣" }, { word: "jacket", translate: "夾克" }, { word: "suit", translate: "套裝" },
        { word: "uniform", translate: "制服" }, { word: "pajamas", translate: "睡衣" }, { word: "underwear", translate: "內衣" },
        { word: "swimsuit", translate: "泳裝" }, { word: "socks", translate: "襪子" }, { word: "shoes", translate: "鞋子" },
        { word: "slippers", translate: "拖鞋" }, { word: "sneakers", translate: "球鞋" }, { word: "pocket", translate: "口袋" },
        { word: "backpack", translate: "後背包" }, { word: "bag", translate: "袋子" }, { word: "purse", translate: "錢包" },
        { word: "wallet", translate: "皮夾" }, { word: "belt", translate: "皮帶" }, { word: "button", translate: "鈕扣" },
        { word: "cap", translate: "鴨舌帽" }, { word: "hat", translate: "帽子" }, { word: "glove", translate: "手套" },
        { word: "scarf", translate: "圍巾" }, { word: "tie", translate: "領帶" }, { word: "glasses", translate: "眼鏡" },
        { word: "contact lens", translate: "隱形眼鏡" }, { word: "earrings", translate: "耳環" }, { word: "necklace", translate: "項鍊" },
        { word: "ring", translate: "戒指" }, { word: "watch", translate: "手錶" }, { word: "handkerchief", translate: "手帕" },
        { word: "mask", translate: "口罩" }, { word: "hanger", translate: "衣架" }, { word: "fit", translate: "合身" },
        { word: "iron", translate: "熨燙" }, { word: "wear", translate: "穿著" }, { word: "fashionable", translate: "時尚的" },
        { word: "color", translate: "顏色" }, { word: "colorful", translate: "多采多姿的" }, { word: "black", translate: "黑色的" },
        { word: "white", translate: "白色的" }, { word: "gray", translate: "灰色的" }, { word: "red", translate: "紅色的" },
        { word: "pink", translate: "粉紅色的" }, { word: "yellow", translate: "黃色的" }, { word: "green", translate: "綠色的" },
        { word: "blue", translate: "藍色的" }, { word: "purple", translate: "紫色的" }, { word: "brown", translate: "棕色的" },
        { word: "golden", translate: "金色的" }, { word: "silver", translate: "銀色的" }
    ],
    "12. 休閒與數字": [
        { word: "festival", translate: "節日" }, { word: "Easter", translate: "復活節" }, { word: "Halloween", translate: "萬聖節" },
        { word: "birthday", translate: "生日" }, { word: "balloon", translate: "汽球" }, { word: "candle", translate: "蠟燭" },
        { word: "card", translate: "卡片" }, { word: "gift", translate: "禮物" }, { word: "party", translate: "派對" },
        { word: "bless", translate: "祝福" }, { word: "celebrate", translate: "慶祝" }, { word: "cheer", translate: "歡呼" },
        { word: "advertisement", translate: "廣告" }, { word: "broadcast", translate: "廣播" }, { word: "cable", translate: "有線電視" },
        { word: "cartoon", translate: "卡通" }, { word: "drama", translate: "戲劇" }, { word: "news", translate: "新聞" },
        { word: "movie", translate: "電影" }, { word: "channel", translate: "頻道" }, { word: "program", translate: "節目" },
        { word: "camera", translate: "相機" }, { word: "film", translate: "電影" }, { word: "tape", translate: "錄音帶" },
        { word: "photo", translate: "相片" }, { word: "picture", translate: "圖片" }, { word: "video", translate: "影片" },
        { word: "scene", translate: "景色" }, { word: "live", translate: "直播的" }, { word: "record", translate: "錄音" },
        { word: "sports", translate: "運動" }, { word: "exercise", translate: "運動" }, { word: "ball", translate: "球" },
        { word: "badminton", translate: "羽毛球" }, { word: "baseball", translate: "棒球" }, { word: "basketball", translate: "籃球" },
        { word: "bowling", translate: "保齡球" }, { word: "dodge ball", translate: "躲避球" }, { word: "football", translate: "美式足球" },
        { word: "golf", translate: "高爾夫球" }, { word: "soccer", translate: "足球" }, { word: "table tennis", translate: "乒乓球" },
        { word: "tennis", translate: "網球" }, { word: "volleyball", translate: "排球" }, { word: "frisbee", translate: "飛盤" },
        { word: "roller blade", translate: "直排輪" }, { word: "roller skate", translate: "輪式溜冰鞋" }, { word: "seesaw", translate: "蹺蹺板" },
        { word: "slide", translate: "滑梯" }, { word: "softball", translate: "壘球" }, { word: "swim", translate: "游泳" },
        { word: "jog", translate: "慢跑" }, { word: "skate", translate: "溜冰" }, { word: "ski", translate: "滑雪" },
        { word: "surf", translate: "衝浪" }, { word: "band", translate: "樂團" }, { word: "music", translate: "音樂" },
        { word: "jazz", translate: "爵士樂" }, { word: "pop music", translate: "流行音樂" }, { word: "instrument", translate: "樂器" },
        { word: "drum", translate: "鼓" }, { word: "flute", translate: "長笛" }, { word: "guitar", translate: "吉他" },
        { word: "piano", translate: "鋼琴" }, { word: "trumpet", translate: "小喇叭" }, { word: "violin", translate: "小提琴" },
        { word: "string", translate: "弦" }, { word: "play", translate: "玩" }, { word: "hobby", translate: "嗜好" },
        { word: "interest", translate: "興趣" }, { word: "camp", translate: "露營" }, { word: "dance", translate: "跳舞" },
        { word: "draw", translate: "畫畫" }, { word: "hike", translate: "健行" }, { word: "paint", translate: "畫圖" },
        { word: "sing", translate: "唱歌" }, { word: "amount", translate: "總數" }, { word: "number", translate: "號碼" },
        { word: "zero", translate: "零" }, { word: "one", translate: "一" }, { word: "two", translate: "二" },
        { word: "three", translate: "三" }, { word: "four", translate: "四" }, { word: "five", translate: "五" },
        { word: "six", translate: "六" }, { word: "seven", translate: "七" }, { word: "eight", translate: "八" },
        { word: "nine", translate: "九" }, { word: "ten", translate: "十" }, { word: "eleven", translate: "十一" },
        { word: "twelve", translate: "十二" }, { word: "thirteen", translate: "十三" }, { word: "fourteen", translate: "十四" },
        { word: "fifteen", translate: "十五" }, { word: "sixteen", translate: "十六" }, { word: "seventeen", translate: "十七" },
        { word: "eighteen", translate: "十八" }, { word: "nineteen", translate: "十九" }, { word: "twenty", translate: "二十" },
        { word: "thirty", translate: "三十" }, { word: "forty", translate: "四十" }, { word: "fifty", translate: "五十" },
        { word: "sixty", translate: "六十" }, { word: "seventy", translate: "七十" }, { word: "eighty", translate: "八十" },
        { word: "ninety", translate: "九十" }, { word: "count", translate: "計算" }, { word: "divide", translate: "除" },
        { word: "minus", translate: "減" }, { word: "plus", translate: "加" }, { word: "first", translate: "第一" },
        { word: "second", translate: "第二" }, { word: "third", translate: "第三" }, { word: "angle", translate: "角度" },
        { word: "size", translate: "大小" }, { word: "centimeter", translate: "公分" }, { word: "inch", translate: "英吋" },
        { word: "meter", translate: "公尺" }, { word: "kilometer", translate: "公里" }, { word: "mile", translate: "英哩" },
        { word: "gram", translate: "公克" }, { word: "kilogram", translate: "公斤" }, { word: "liter", translate: "公升" },
        { word: "hundred", translate: "百" }, { word: "thousand", translate: "千" }, { word: "million", translate: "百萬" },
        { word: "quarter", translate: "四分之一" }, { word: "measure", translate: "測量" }, { word: "heat", translate: "熱度" },
        { word: "height", translate: "高度" }, { word: "weight", translate: "重量" }, { word: "heavy", translate: "重的" },
        { word: "over-weight", translate: "超重的" }, { word: "high", translate: "高的" }, { word: "low", translate: "低的" },
        { word: "shape", translate: "形狀" }, { word: "rectangle", translate: "長方形" }, { word: "triangle", translate: "三角形" },
        { word: "round", translate: "圓形的" }
    ],
    "13. 形容詞與代名詞": [
        { word: "alike", translate: "相似的" }, { word: "similar", translate: "相似的" }, { word: "alone", translate: "單獨的" },
        { word: "single", translate: "單一的" }, { word: "blank", translate: "空白的" }, { word: "empty", translate: "空的" },
        { word: "else", translate: "另外的" }, { word: "another", translate: "另一個" }, { word: "other", translate: "其他的" },
        { word: "excellent", translate: "傑出的" }, { word: "marvelous", translate: "了不起的" }, { word: "important", translate: "重要的" },
        { word: "main", translate: "主要的" }, { word: "necessary", translate: "必要的" }, { word: "interested", translate: "感興趣的" },
        { word: "interesting", translate: "有趣的" }, { word: "pop", translate: "流行的" }, { word: "popular", translate: "受歡迎的" },
        { word: "asleep", translate: "睡著的" }, { word: "sleepy", translate: "想睡的" }, { word: "tired", translate: "疲倦的" },
        { word: "total", translate: "全部的" }, { word: "whole", translate: "完整的" }, { word: "helpful", translate: "有幫助的" },
        { word: "useful", translate: "有用的" }, { word: "broad", translate: "寬闊的" }, { word: "wide", translate: "寬的" },
        { word: "narrow", translate: "窄的" }, { word: "basic", translate: "基本的" }, { word: "common", translate: "常見的" },
        { word: "usual", translate: "通常的" }, { word: "general", translate: "一般的" }, { word: "ordinary", translate: "平常的" },
        { word: "regular", translate: "定期的" }, { word: "rare", translate: "稀有的" }, { word: "special", translate: "特別的" },
        { word: "unique", translate: "獨特的" }, { word: "difficult", translate: "困難的" }, { word: "hard", translate: "困難的" },
        { word: "easy", translate: "容易的" }, { word: "simple", translate: "簡單的" }, { word: "real", translate: "真正的" },
        { word: "true", translate: "真的" }, { word: "false", translate: "錯誤的" }, { word: "correct", translate: "正確的" },
        { word: "fantastic", translate: "極好的" }, { word: "fine", translate: "美好的" }, { word: "great", translate: "不錯的" },
        { word: "nice", translate: "美好的" }, { word: "perfect", translate: "完美的" }, { word: "wonderful", translate: "極好的" },
        { word: "terrific", translate: "非常好的" }, { word: "terrible", translate: "糟糕的" }, { word: "large", translate: "巨大的" },
        { word: "big", translate: "大的" }, { word: "small", translate: "小的" }, { word: "least", translate: "最小的" },
        { word: "little", translate: "一點點" }, { word: "primary", translate: "首要的" }, { word: "secondary", translate: "第二的" },
        { word: "alive", translate: "活著的" }, { word: "dead", translate: "死的" }, { word: "bright", translate: "明亮的" },
        { word: "dark", translate: "黑暗的" }, { word: "forward", translate: "前面的" }, { word: "backward", translate: "向後的" },
        { word: "safe", translate: "安全的" }, { word: "dangerous", translate: "危險的" }, { word: "same", translate: "同樣的" },
        { word: "different", translate: "不同的" }, { word: "early", translate: "早的" }, { word: "late", translate: "遲到的" },
        { word: "fancy", translate: "高級的" }, { word: "plain", translate: "樸素的" }, { word: "fast", translate: "快的" },
        { word: "quick", translate: "迅速的" }, { word: "slow", translate: "慢慢的" }, { word: "impossible", translate: "不可能的" },
        { word: "possible", translate: "可能的" }, { word: "likely", translate: "有可能的" }, { word: "distant", translate: "遙遠的" },
        { word: "near", translate: "近的" }, { word: "new", translate: "新的" }, { word: "old", translate: "舊的" },
        { word: "wrong", translate: "錯誤的" }, { word: "right", translate: "正確的" }, { word: "left", translate: "左邊的" },
        { word: "major", translate: "大多數的" }, { word: "minor", translate: "次要的" }, { word: "maximum", translate: "最大限度的" },
        { word: "medium", translate: "中等的" }, { word: "middle", translate: "中間的" }, { word: "negative", translate: "負面的" },
        { word: "positive", translate: "正面的" }, { word: "noisy", translate: "喧鬧的" }, { word: "peaceful", translate: "和平的" },
        { word: "quiet", translate: "安靜的" }, { word: "silent", translate: "寂靜的" }, { word: "rich", translate: "富有的" },
        { word: "poor", translate: "貧困的" }, { word: "private", translate: "私人的" }, { word: "public", translate: "公共的" },
        { word: "able", translate: "有能力的" }, { word: "absent", translate: "缺席的" }, { word: "active", translate: "主動的" },
        { word: "available", translate: "有空的" }, { word: "boring", translate: "令人乏味的" }, { word: "born", translate: "天生的" },
        { word: "brave", translate: "勇敢的" }, { word: "busy", translate: "忙碌的" }, { word: "central", translate: "中心的" },
        { word: "certain", translate: "確定的" }, { word: "classical", translate: "古典的" }, { word: "clear", translate: "清楚的" },
        { word: "comfortable", translate: "舒適的" }, { word: "convenient", translate: "方便的" }, { word: "crazy", translate: "瘋狂的" },
        { word: "crowded", translate: "擁擠的" }, { word: "cruel", translate: "殘忍的" }, { word: "curious", translate: "好奇的" },
        { word: "dear", translate: "親愛的" }, { word: "deep", translate: "深的" }, { word: "double", translate: "雙重的" },
        { word: "electric", translate: "電的" }, { word: "energetic", translate: "精力充沛的" }, { word: "enough", translate: "充足的" },
        { word: "exciting", translate: "令人興奮的" }, { word: "extra", translate: "額外的" }, { word: "fair", translate: "公平的" },
        { word: "famous", translate: "著名的" }, { word: "favorite", translate: "最愛的" }, { word: "final", translate: "最終的" },
        { word: "formal", translate: "正式的" }, { word: "former", translate: "早前的" }, { word: "frank", translate: "坦白的" },
        { word: "fresh", translate: "新鮮的" }, { word: "full", translate: "充滿的" }, { word: "gold", translate: "金製的" },
        { word: "greedy", translate: "貪婪的" }, { word: "homesick", translate: "想家的" }, { word: "horrible", translate: "可怕的" },
        { word: "independent", translate: "獨立的" }, { word: "instant", translate: "即時的" }, { word: "next", translate: "下一個" },
        { word: "last", translate: "最後的" }, { word: "latest", translate: "最新的" }, { word: "latter", translate: "後者的" },
        { word: "long", translate: "長的" }, { word: "loud", translate: "大聲的" }, { word: "lucky", translate: "好運的" },
        { word: "magic", translate: "有魔力的" }, { word: "mass", translate: "大量的" }, { word: "married", translate: "已婚的" },
        { word: "not", translate: "不是的" }, { word: "off", translate: "關著的" }, { word: "pale", translate: "蒼白的" },
        { word: "patient", translate: "有耐心的" }, { word: "personal", translate: "私人的" }, { word: "pleasant", translate: "愉悅的" },
        { word: "precious", translate: "珍貴的" }, { word: "ready", translate: "準備好的" }, { word: "scared", translate: "受到驚嚇的" },
        { word: "serious", translate: "嚴重的" }, { word: "sharp", translate: "鋒利的" }, { word: "skillful", translate: "有技術的" },
        { word: "sneaky", translate: "鬼鬼祟祟的" }, { word: "social", translate: "社會的" }, { word: "straight", translate: "直的" },
        { word: "strange", translate: "奇怪的" }, { word: "successful", translate: "成功的" }, { word: "such", translate: "如此的" },
        { word: "sudden", translate: "突然的" }, { word: "super", translate: "超級的" }, { word: "sure", translate: "有把握的" },
        { word: "thick", translate: "厚的" }, { word: "tidy", translate: "整齊的" }, { word: "tiny", translate: "微小的" },
        { word: "touch", translate: "感動" }, { word: "upper", translate: "較高的" }, { word: "valuable", translate: "有價值的" },
        { word: "welcome", translate: "受歡迎的" }, { word: "wet", translate: "潮濕的" }, { word: "wild", translate: "野生的" },
        { word: "beautiful", translate: "漂亮的" }, { word: "pretty", translate: "漂亮的" }, { word: "ugly", translate: "醜的" },
        { word: "chubby", translate: "圓胖的" }, { word: "fat", translate: "胖的" }, { word: "cute", translate: "可愛的" },
        { word: "lovely", translate: "可愛的" }, { word: "handsome", translate: "英俊的" }, { word: "nice-looking", translate: "外表好看的" },
        { word: "tall", translate: "高的" }, { word: "short", translate: "矮的" }, { word: "skinny", translate: "瘦到皮包骨的" },
        { word: "slender", translate: "修長的" }, { word: "slim", translate: "苗條的" }, { word: "thin", translate: "瘦的" },
        { word: "elder", translate: "年長的" }, { word: "young", translate: "年輕的" }, { word: "beauty", translate: "美人" }
    ],
    "14. 動作與其他": [
        { word: "appreciate", translate: "感謝" }, { word: "thank", translate: "謝謝" }, { word: "beat", translate: "擊敗" },
        { word: "hit", translate: "打擊" }, { word: "knock", translate: "敲" }, { word: "begin", translate: "開始" },
        { word: "start", translate: "開始" }, { word: "believe", translate: "相信" }, { word: "trust", translate: "信任" },
        { word: "choose", translate: "選擇" }, { word: "pick", translate: "挑選" }, { word: "select", translate: "挑選" },
        { word: "find", translate: "發現" }, { word: "search", translate: "搜尋" }, { word: "seek", translate: "尋找" },
        { word: "describe", translate: "描述" }, { word: "explain", translate: "解釋" }, { word: "express", translate: "表示" },
        { word: "forgive", translate: "原諒" }, { word: "pardon", translate: "寬恕" }, { word: "collect", translate: "收集" },
        { word: "gather", translate: "聚集" }, { word: "expect", translate: "期望" }, { word: "hope", translate: "希望" },
        { word: "wish", translate: "希望" }, { word: "assume", translate: "假設" }, { word: "guess", translate: "猜測" },
        { word: "hop", translate: "跳過" }, { word: "jump", translate: "跳" }, { word: "know", translate: "知道" },
        { word: "understand", translate: "理解" }, { word: "realize", translate: "了解" }, { word: "laugh", translate: "笑" },
        { word: "smile", translate: "微笑" }, { word: "offer", translate: "提供" }, { word: "provide", translate: "提供" },
        { word: "serve", translate: "服務" }, { word: "raise", translate: "舉起" }, { word: "rise", translate: "升起" },
        { word: "shout", translate: "大叫" }, { word: "yell", translate: "吼叫" }, { word: "accept", translate: "接受" },
        { word: "refuse", translate: "拒絕" }, { word: "reject", translate: "拒絕" }, { word: "appear", translate: "出現" },
        { word: "disappear", translate: "消失" }, { word: "arrive", translate: "到達" }, { word: "leave", translate: "離開" },
        { word: "stay", translate: "停留" }, { word: "borrow", translate: "借入" }, { word: "lend", translate: "借出" },
        { word: "carry", translate: "運載" }, { word: "catch", translate: "抓住" }, { word: "throw", translate: "投擲" },
        { word: "open", translate: "打開" }, { word: "close", translate: "關上" }, { word: "go", translate: "去" },
        { word: "come", translate: "來" }, { word: "damage", translate: "損害" }, { word: "repair", translate: "修理" },
        { word: "decrease", translate: "減少" }, { word: "increase", translate: "增加" }, { word: "upload", translate: "上傳" },
        { word: "download", translate: "下載" }, { word: "succeed", translate: "成功" }, { word: "fail", translate: "失敗" },
        { word: "remember", translate: "記得" }, { word: "forget", translate: "忘記" }, { word: "gain", translate: "獲得" },
        { word: "lose", translate: "失去" }, { word: "pull", translate: "推著" }, { word: "push", translate: "推" },
        { word: "send", translate: "發送" }, { word: "receive", translate: "收到" }, { word: "turn", translate: "轉動" },
        { word: "shut", translate: "關閉" }, { word: "sit", translate: "坐" }, { word: "stand", translate: "站" },
        { word: "sleep", translate: "睡" }, { word: "wake", translate: "醒來" }, { word: "act", translate: "行動" },
        { word: "add", translate: "添加" }, { word: "advise", translate: "建議" }, { word: "affect", translate: "影響" },
        { word: "agree", translate: "同意" }, { word: "aim", translate: "瞄準" }, { word: "allow", translate: "允許" },
        { word: "apologize", translate: "道歉" }, { word: "argue", translate: "爭論" }, { word: "arrange", translate: "安排" },
        { word: "ask", translate: "問" }, { word: "attack", translate: "攻擊" }, { word: "avoid", translate: "避免" },
        { word: "bark", translate: "吠" }, { word: "base", translate: "根據" }, { word: "become", translate: "成為" },
        { word: "behave", translate: "表現" }, { word: "belong", translate: "屬於" }, { word: "bite", translate: "咬" },
        { word: "blame", translate: "責備" }, { word: "blow", translate: "吹" }, { word: "bother", translate: "打擾" },
        { word: "bow", translate: "鞠躬" }, { word: "break", translate: "弄壞" }, { word: "bring", translate: "帶來" },
        { word: "build", translate: "建造" }, { word: "burn", translate: "燃燒" }, { word: "burst", translate: "爆裂" },
        { word: "calm", translate: "使平靜" }, { word: "cancel", translate: "取消" }, { word: "change", translate: "改變" },
        { word: "chase", translate: "追逐" }, { word: "cheat", translate: "欺騙" }, { word: "check", translate: "檢查" },
        { word: "climb", translate: "攀爬" }, { word: "comment", translate: "評論" }, { word: "compare", translate: "比較" },
        { word: "complain", translate: "抱怨" }, { word: "complete", translate: "完成" }, { word: "continue", translate: "繼續" },
        { word: "control", translate: "控制" }, { word: "cover", translate: "覆蓋" }, { word: "create", translate: "創造" },
        { word: "cross", translate: "跨過" }, { word: "pass", translate: "通過" }, { word: "cry", translate: "哭泣" },
        { word: "cut", translate: "切割" }, { word: "deal", translate: "處理" }, { word: "debate", translate: "辯論" },
        { word: "decide", translate: "決定" }, { word: "define", translate: "定義" }, { word: "deliver", translate: "遞送" },
        { word: "depend", translate: "依賴" }, { word: "detect", translate: "察覺" }, { word: "develop", translate: "發展" },
        { word: "die", translate: "死" }, { word: "dig", translate: "挖" }, { word: "direct", translate: "指揮" },
        { word: "discover", translate: "發現" }, { word: "discuss", translate: "討論" }, { word: "doubt", translate: "懷疑" },
        { word: "dream", translate: "作夢" }, { word: "dry", translate: "變乾" }, { word: "earn", translate: "賺到" },
        { word: "ease", translate: "使放鬆" }, { word: "embarrass", translate: "使困窘" }, { word: "emphasize", translate: "強調" },
        { word: "enjoy", translate: "享受" }, { word: "enter", translate: "進入" }, { word: "equal", translate: "等於" },
        { word: "excite", translate: "使興奮" }, { word: "exist", translate: "存在" }, { word: "fall", translate: "落下" },
        { word: "feed", translate: "餵食" }, { word: "fight", translate: "打架" }, { word: "fill", translate: "充滿" },
        { word: "finish", translate: "結束" }, { word: "fix", translate: "修理" }, { word: "fly", translate: "飛" },
        { word: "focus", translate: "專注" }, { word: "follow", translate: "跟隨" }, { word: "frighten", translate: "使害怕" },
        { word: "get", translate: "得到" }, { word: "give", translate: "給" }, { word: "greet", translate: "問候" },
        { word: "guide", translate: "引導" }, { word: "hammer", translate: "敲打" }, { word: "handle", translate: "處理" },
        { word: "hang", translate: "掛起" }, { word: "happen", translate: "發生" }, { word: "have", translate: "擁有" },
        { word: "help", translate: "幫助" }, { word: "hide", translate: "藏起來" }, { word: "hold", translate: "抓住" },
        { word: "hug", translate: "擁抱" }, { word: "hunt", translate: "狩獵" }, { word: "hurry", translate: "急忙" },
        { word: "ignore", translate: "忽視" }, { word: "imagine", translate: "想像" }, { word: "improve", translate: "改善" },
        { word: "include", translate: "包含" }, { word: "indicate", translate: "指出" }, { word: "show", translate: "顯示" },
        { word: "insist", translate: "堅持" }, { word: "inspire", translate: "激勵" }, { word: "introduce", translate: "介紹" },
        { word: "invent", translate: "發明" }, { word: "invite", translate: "邀請" }, { word: "join", translate: "加入" },
        { word: "kick", translate: "踢" }, { word: "keep", translate: "保持" }, { word: "kill", translate: "殺害" },
        { word: "lack", translate: "缺乏" }, { word: "lay", translate: "放置" }, { word: "lead", translate: "領導" },
        { word: "let", translate: "讓" }, { word: "lick", translate: "舔" }, { word: "lie", translate: "說謊" },
        { word: "lift", translate: "舉起" }, { word: "limit", translate: "限制" }, { word: "lock", translate: "鎖住" },
        { word: "make", translate: "製做" }, { word: "marry", translate: "結婚" }, { word: "master", translate: "精通" },
        { word: "match", translate: "相配" }, { word: "mean", translate: "表示意思" }, { word: "meet", translate: "遇見" },
        { word: "mind", translate: "介意" }, { word: "miss", translate: "錯過" }, { word: "mix", translate: "混合" },
        { word: "move", translate: "移動" }, { word: "need", translate: "需要" }, { word: "nod", translate: "點頭" },
        { word: "notice", translate: "注意到" }, { word: "obey", translate: "服從" }, { word: "object", translate: "反對" },
        { word: "omit", translate: "省略" }, { word: "own", translate: "擁有" }, { word: "pack", translate: "打包" },
        { word: "pause", translate: "暫停" }, { word: "please", translate: "取悅" }, { word: "pollute", translate: "污染" },
        { word: "practice", translate: "練習" }, { word: "praise", translate: "讚美" }, { word: "pray", translate: "祈求" },
        { word: "prepare", translate: "準備" }, { word: "print", translate: "印刷" }, { word: "produce", translate: "製造" },
        { word: "promise", translate: "承諾" }, { word: "pronounce", translate: "發音" }, { word: "protect", translate: "保護" },
        { word: "pump", translate: "抽送" }, { word: "punish", translate: "處罰" }, { word: "put", translate: "放置" },
        { word: "puzzle", translate: "使困惑" }, { word: "reach", translate: "抵達" }, { word: "read", translate: "閱讀" },
        { word: "recover", translate: "恢復" }, { word: "recycle", translate: "回收" }, { word: "remind", translate: "提醒" },
        { word: "repeat", translate: "重複" }, { word: "rest", translate: "休息" }, { word: "return", translate: "返回" },
        { word: "revise", translate: "修訂" }, { word: "rob", translate: "搶劫" }, { word: "roll", translate: "滾動" },
        { word: "rub", translate: "磨擦" }, { word: "ruin", translate: "毀壞" }, { word: "run", translate: "跑" },
        { word: "walk", translate: "走路" }, { word: "rush", translate: "衝" }, { word: "satisfy", translate: "使滿意" },
        { word: "save", translate: "拯救" }, { word: "score", translate: "得分" }, { word: "seem", translate: "似乎" },
        { word: "set", translate: "設置" }, { word: "shake", translate: "搖動" }, { word: "share", translate: "分享" },
        { word: "shoot", translate: "射擊" }, { word: "solve", translate: "解決" }, { word: "spell", translate: "拼寫" },
        { word: "spot", translate: "看到" }, { word: "spread", translate: "擴散" }, { word: "state", translate: "陳述" },
        { word: "steal", translate: "偷竊" }, { word: "strike", translate: "攻擊" }, { word: "suggest", translate: "建議" },
        { word: "support", translate: "支持" }, { word: "surprise", translate: "令驚訝" }, { word: "survive", translate: "倖存" },
        { word: "take", translate: "拿取" }, { word: "teach", translate: "教" }, { word: "tear", translate: "撕裂" },
        { word: "think", translate: "認為" }, { word: "trace", translate: "追蹤" }, { word: "trap", translate: "設陷阱" },
        { word: "travel", translate: "旅行" }, { word: "treasure", translate: "珍愛" }, { word: "underline", translate: "畫底線" },
        { word: "use", translate: "使用" }, { word: "visit", translate: "拜訪" }, { word: "wait", translate: "等待" },
        { word: "want", translate: "想要" }, { word: "wash", translate: "洗" }, { word: "waste", translate: "浪費" },
        { word: "water", translate: "澆水" }, { word: "wave", translate: "揮手" }, { word: "win", translate: "獲勝" },
        { word: "write", translate: "寫作" }, { word: "try", translate: "嘗試" }, { word: "were", translate: "是" },
        { word: "actually", translate: "事實上" }, { word: "again", translate: "再次" }, { word: "ahead", translate: "向前" },
        { word: "almost", translate: "幾乎" }, { word: "nearly", translate: "幾乎" }, { word: "aloud", translate: "大聲地" },
        { word: "already", translate: "已經" }, { word: "even", translate: "甚至" }, { word: "also", translate: "也" },
        { word: "too", translate: "也" }, { word: "altogether", translate: "合計" }, { word: "as", translate: "像一樣" },
        { word: "away", translate: "離開" }, { word: "besides", translate: "此外" }, { word: "up", translate: "向上" },
        { word: "down", translate: "向下" }, { word: "upstairs", translate: "樓上" }, { word: "downstairs", translate: "樓下" },
        { word: "either", translate: "也(否定)" }, { word: "especially", translate: "特別地" }, { word: "far", translate: "遙遠地" },
        { word: "finally", translate: "最後" }, { word: "however", translate: "然而" }, { word: "just", translate: "只是" },
        { word: "later", translate: "較晚" }, { word: "maybe", translate: "可能" }, { word: "perhaps", translate: "或許" },
        { word: "probably", translate: "很有可能" }, { word: "yes", translate: "是的" }, { word: "no", translate: "不是" },
        { word: "once", translate: "一次" }, { word: "twice", translate: "兩次" }, { word: "only", translate: "只是" },
        { word: "quite", translate: "非常地" }, { word: "so", translate: "非常" }, { word: "very", translate: "非常地" },
        { word: "rather", translate: "寧可" }, { word: "really", translate: "真正地" }, { word: "soon", translate: "不久" },
        { word: "still", translate: "仍然" }, { word: "then", translate: "然後" }, { word: "therefore", translate: "因此" },
        { word: "together", translate: "一起" }, { word: "yet", translate: "尚未" }, { word: "about", translate: "關於" },
        { word: "against", translate: "反對" }, { word: "along", translate: "沿著" }, { word: "beyond", translate: "越過" },
        { word: "except", translate: "除之外" }, { word: "for", translate: "為了" }, { word: "from", translate: "從" },
        { word: "since", translate: "自從" }, { word: "into", translate: "到裡面" }, { word: "like", translate: "像" },
        { word: "of", translate: "的" }, { word: "out", translate: "向外" }, { word: "outside", translate: "外面" },
        { word: "through", translate: "穿過" }, { word: "till", translate: "直到" }, { word: "until", translate: "直到" },
        { word: "to", translate: "到" }, { word: "toward", translate: "朝向" }, { word: "with", translate: "和一起" },
        { word: "without", translate: "沒有" }, { word: "a/an", translate: "一個" }, { word: "a few", translate: "幾個" },
        { word: "a little", translate: "一點" }, { word: "a lot", translate: "大量" }, { word: "few", translate: "一些" },
        { word: "less", translate: "較少的" }, { word: "more", translate: "更多的" }, { word: "many", translate: "許多" },
        { word: "much", translate: "許多的" }, { word: "most", translate: "大部份的" }, { word: "several", translate: "幾個的" },
        { word: "some", translate: "一些" }, { word: "couple", translate: "對" }, { word: "pair", translate: "一雙" },
        { word: "dozen", translate: "一打" }, { word: "drop", translate: "一滴" }, { word: "piece", translate: "一片" },
        { word: "pile", translate: "一堆" }, { word: "loaf", translate: "一條" }, { word: "bundle", translate: "一捆" },
        { word: "any", translate: "任何一個" }, { word: "anyone", translate: "任何人" }, { word: "anything", translate: "任何事" },
        { word: "anywhere", translate: "任何地方" }, { word: "each", translate: "每個" }, { word: "every", translate: "每一個" },
        { word: "everyone", translate: "每個人" }, { word: "everything", translate: "每件事" }, { word: "everywhere", translate: "到處" },
        { word: "nobody", translate: "沒有人" }, { word: "none", translate: "沒有一個" }, { word: "nothing", translate: "沒什麼" },
        { word: "someone", translate: "某人" }, { word: "something", translate: "某事" }, { word: "sometimes", translate: "有時候" },
        { word: "somewhere", translate: "某處" }, { word: "what", translate: "什麼" }, { word: "when", translate: "何時" },
        { word: "where", translate: "在哪裡" }, { word: "whether", translate: "是否" }, { word: "which", translate: "哪個" },
        { word: "who", translate: "誰" }, { word: "whose", translate: "誰的" }, { word: "why", translate: "為什麼" },
        { word: "how", translate: "如何" }, { word: "we", translate: "我們" }, { word: "you", translate: "你" },
        { word: "he", translate: "他" }, { word: "she", translate: "她" }, { word: "it", translate: "牠" },
        { word: "they", translate: "他們" }, { word: "myself", translate: "我自己" }, { word: "themselves", translate: "他們自己" },
        { word: "oneself", translate: "自己" }, { word: "her", translate: "她的" }, { word: "his", translate: "他的" },
        { word: "its", translate: "它的" }, { word: "my", translate: "我的" }, { word: "our", translate: "我們的" },
        { word: "their", translate: "他們的" }, { word: "your", translate: "你的" }, { word: "here", translate: "這裡" },
        { word: "there", translate: "那裡" }, { word: "the", translate: "這" }, { word: "this", translate: "這" },
        { word: "that", translate: "那" }, { word: "these", translate: "這些" }, { word: "those", translate: "那些" },
        { word: "above", translate: "在上面" }, { word: "over", translate: "在之上" }, { word: "on", translate: "在上面" },
        { word: "upon", translate: "在之上" }, { word: "below", translate: "在下面" }, { word: "under", translate: "在下面" },
        { word: "across", translate: "在對面" }, { word: "behind", translate: "在後面" }, { word: "among", translate: "在之中" },
        { word: "between", translate: "在之間" }, { word: "around", translate: "在附近" }, { word: "beside", translate: "在旁邊" },
        { word: "by", translate: "在旁邊" }, { word: "in", translate: "在裡面" }, { word: "inside", translate: "在裡面" },
        { word: "at", translate: "在地點" }, { word: "before", translate: "在之前" }, { word: "after", translate: "在以後" },
        { word: "during", translate: "在期間" }, { word: "always", translate: "總是" }, { word: "usually", translate: "通常" },
        { word: "often", translate: "經常" }, { word: "seldom", translate: "很少" }, { word: "hardly", translate: "幾乎不" },
        { word: "never", translate: "從不" }, { word: "hello", translate: "哈囉" }, { word: "hi", translate: "嗨" },
        { word: "hey", translate: "嘿" }, { word: "goodbye", translate: "再見" }, { word: "OK", translate: "可以的" },
        { word: "could", translate: "能" }, { word: "do", translate: "做" }, { word: "may", translate: "可能" },
        { word: "must", translate: "必須" }, { word: "shall", translate: "將要" }, { word: "should", translate: "應該" },
        { word: "and", translate: "和" }, { word: "although", translate: "雖然" }, { word: "but", translate: "但是" },
        { word: "because", translate: "因為" }, { word: "if", translate: "假如" }, { word: "neither", translate: "兩者都不" },
        { word: "nor", translate: "也不" }, { word: "or", translate: "或者" }, { word: "than", translate: "比" },
        { word: "while", translate: "當時" }, { word: "direction", translate: "說明" }, { word: "character", translate: "性格" },
        { word: "role", translate: "角色" }, { word: "angel", translate: "天使" }, { word: "dragon", translate: "龍" },
        { word: "ghost", translate: "鬼" }, { word: "god", translate: "上帝" }, { word: "monster", translate: "怪物" },
        { word: "customer", translate: "顧客" }, { word: "guest", translate: "客人" }, { word: "passenger", translate: "乘客" },
        { word: "enemy", translate: "敵人" }, { word: "neighbor", translate: "鄰居" }, { word: "friend", translate: "朋友" },
        { word: "partner", translate: "夥伴" }, { word: "stranger", translate: "陌生人" }, { word: "visitor", translate: "遊客" },
        { word: "fool", translate: "笨蛋" }, { word: "genius", translate: "天才" }, { word: "giant", translate: "巨人" },
        { word: "hero", translate: "英雄" }, { word: "hunter", translate: "獵人" }, { word: "host", translate: "主持人" },
        { word: "leader", translate: "領導者" }, { word: "player", translate: "選手" }, { word: "thief", translate: "小偷" },
        { word: "king", translate: "國王" }, { word: "queen", translate: "皇后" }, { word: "prince", translate: "王子" },
        { word: "princess", translate: "公主" }, { word: "servant", translate: "僕人" }
    ]
};